### ISSUE TITLE
retrieve conversations

### ISSUE THREAD

**Issue by kag0** [blackdoor-specialteams/intertalk#6]
`GET /conversations`
returns array of array of conversation participants

**Comment by yacklebeam** [comment]
could you provide a use case for this?
will it only conversations the current user is part of?

**Comment by kag0** [comment]
Use case would be when you log in, this data would enable you to populate the sidebar with a list of conversations (like hangouts or signal, etc).
Yes, it would only be ones the user is part of.

**Comment by yacklebeam** [comment]
So would it be an array of arrays of participants or an array of convo ids?

**Comment by kag0** [comment]
array of arrays of participants
